name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
    - name: Clone source code
      run: |
        sudo git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sudo ./dl_toolchain.sh
        sudo mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: DIR-882-5.0
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CURL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_UVC/d' .config # uvc 摄像头驱动
        sed -i '/CONFIG_FIRMWARE_INCLUDE_AUDIO/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SFTP/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPDUMP/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD36/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_PARTED/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HDPARM/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FTPD/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LPRD/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_U2EC/d' .config 
        sed -i '/CONFIG_FIRMWARE_ENABLE_USB/d' .config 
        sed -i '/CONFIG_FIRMWARE_ENABLE_UFSD/d' .config 
        sed -i '/CONFIG_FIRMWARE_ENABLE_FAT/d' .config 
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXFAT/d' .config 
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT2/d' .config 
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT3/d' .config 
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT4/d' .config 
        sed -i '/CONFIG_FIRMWARE_ENABLE_FUSE/d' .config 
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SERIAL/d' .config 
        #########################################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_CURL=n" >> .config # 去除用于 Drcom 的工具
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config # 去除用于 Drcom 的工具
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config # 去除可用于锐捷的 eap 客户端
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config # 去除南工网络客户端
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> .config # 去除用于 KMS 的工具
        echo "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> .config # 去除用于 IPTV 的 XUPNP
        echo "CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_UVC=n" >> .config # 去除 uvc 摄像头驱动
        echo "CONFIG_FIRMWARE_INCLUDE_AUDIO=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_EAP_PEAP=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_SFTP=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_TCPDUMP=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD36=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_PARTED=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_HDPARM=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_FTPD=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_LPRD=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_U2EC=n" >> .config 
        echo "CONFIG_FIRMWARE_ENABLE_USB=n" >> .config 
        echo "CONFIG_FIRMWARE_ENABLE_UFSD=n" >> .config 
        echo "CONFIG_FIRMWARE_ENABLE_FAT=n" >> .config 
        echo "CONFIG_FIRMWARE_ENABLE_EXFAT=n" >> .config 
        echo "CONFIG_FIRMWARE_ENABLE_EXT2=n" >> .config 
        echo "CONFIG_FIRMWARE_ENABLE_EXT3=n" >> .config 
        echo "CONFIG_FIRMWARE_ENABLE_EXT4=n" >> .config 
        echo "CONFIG_FIRMWARE_ENABLE_FUSE=n" >> .config 
        echo "CONFIG_FIRMWARE_INCLUDE_SERIAL=n" >> .config 
        #########################################################################################
        cp -f .config configs/templates/$TNAME.config 
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
